---
- name: Copy UrBackup binary file on client 
  copy:
    src: ../files/urbackup_client_linux_2.5.25.sh
    dest: /tmp/urbackup_client_linux_2.5.25.sh
    mode: '0755'

- name: Install UrBackup client
  shell: |
    sh /tmp/urbackup_client_linux_2.5.25.sh <<EOF
    Y
    5
    EOF
  args:
    creates: /usr/local/urbackup/urbackupclient

- name: Delete file after install
  file:
    path: /tmp/urbackup_client_linux_2.5.25.sh
    state: absent

- name: Replace RESTORE=disabled to RESTORE=server-confirms in /etc/default/urbackupclient
  lineinfile:
    path: /etc/default/urbackupclient
    regexp: '^RESTORE=.*'
    line: 'RESTORE=server-confirms'
#    backup: yes   # uncomment if you don't need backup file

- name: Ensure urbackupclientbackend is started and enabled at boot.
  service:
    name: urbackupclientbackend
    state: started
    enabled: true